services:
  web:
    image: sorz2122/trim2circle
    #Only needed if building the image yourself
    #build: .
    ports:
      - "5000:5000"
    #Only needed if building the image yourself
    #volumes:
    #- .:/app
    #environment:
    #  FLASK_ENV: production
    networks:
      - proxy_net
networks:
  proxy_net:
    external: true
